# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Completo', models.CharField(max_length=200)),
                ('Direccion', models.CharField(max_length=200)),
                ('Anio_nacimiento', models.DateTimeField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Grado', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_materia', models.CharField(max_length=200)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='grados',
            name='Materias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Materia', to='examen.Materia'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='Grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='examen.Grados'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
